### ISSUE TITLE
知识库和问题的向量化方式不同

### ISSUE THREAD

**Issue by currenttime** [yuanzhoulvpi2017/DocumentSearch#5]
知识库中的文件内容的Embedding是用chinese-roberta-wwm-ext向量化模型做的
而输入问题的Embedding是用THUDM/chatglm-6b对话大模型做的
两者之间计算相似度合理吗?为什么不统一用一个模型做?

**Comment by yuanzhoulvpi2017** [comment]
你是不是看错了？你再仔细看看代码

**Comment by currenttime** [comment]
> 啥意思？没看懂

刚才没打全, 问题更新了

**Comment by currenttime** [comment]
> 你是不是看错了？你再仔细看看代码

抱歉抱歉,看错了,弄懂了
